image: fedora:latest

variables:
  DEPS_COMMON: git libtool make ImageMagick autoconf-archive
      wine-core.x86_64 wine-core.i686
      mingw32-gcc-c++ mingw32-winpthreads-static
      mingw64-gcc-c++ mingw64-winpthreads-static
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - dnf install -y $DEPS_COMMON
  - autoreconf -if

fedora-mingw:
  script:
  - mingw64-configure
  - mingw64-make
  - mingw64-make check || { cat test-suite.log ; exit 1; }
  - make distclean
  - mingw32-configure
  - mingw32-make
  - mingw32-make check || { cat test-suite.log ; exit 1; }
